import { useLocation, useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowLeft, ShoppingCart, Download, Check, ExternalLink } from 'lucide-react'
import PageWrapper from '../components/PageWrapper'

export default function BuildSummaryPage() {
  const location = useLocation()
  const navigate = useNavigate()
  const { selectedParts, purpose, budget } = location.state || {}

  // If no data, redirect back
  if (!selectedParts || Object.keys(selectedParts).length === 0) {
    navigate('/pc-builder')
    return null
  }

  const getTotal = () => Object.values(selectedParts).reduce((s, p) => s + Math.min(p.price.amazon, p.price.flipkart), 0)
  const total = getTotal()

  const exportBuild = () => {
    const txt = `🖥️ MY PC BUILD — ${purpose?.toUpperCase() || 'CUSTOM'}\nBudget: ₹${budget?.toLocaleString('en-IN') || 'N/A'}\nTotal: ₹${total.toLocaleString('en-IN')}\n\n${Object.entries(selectedParts).map(([c, p]) => `${c}: ${p.name} — ₹${Math.min(p.price.amazon, p.price.flipkart).toLocaleString('en-IN')}`).join('\n')}\n\nGenerated by PCraft`
    const a = document.createElement('a')
    a.href = URL.createObjectURL(new Blob([txt], { type: 'text/plain' }))
    a.download = `pcraft-build-${Date.now()}.txt`
    a.click()
  }

  return (
    <PageWrapper>
      <div style={{ minHeight: 'calc(100vh - 64px)', background: '#fffef7', padding: '40px 24px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>

          {/* Header */}
          <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}>
            <button onClick={() => navigate('/pc-builder')}
              style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 20px', borderRadius: 10, border: '2px solid #e5e7eb', background: 'white', color: '#6b7280', fontSize: 14, fontWeight: 700, cursor: 'pointer', marginBottom: 24, transition: 'all 0.2s' }}
              onMouseEnter={e => e.target.style.background = '#f3f4f6'}
              onMouseLeave={e => e.target.style.background = 'white'}>
              <ArrowLeft size={16} /> Back to Builder
            </button>

            <div style={{ textAlign: 'center', marginBottom: 40 }}>
              <span style={{ display: 'inline-block', fontSize: 11, fontWeight: 800, color: '#1a1a1a', background: '#f5c800', padding: '4px 14px', borderRadius: 20, letterSpacing: '1.5px', textTransform: 'uppercase', marginBottom: 14 }}>
                YOUR BUILD SUMMARY
              </span>
              <h1 style={{ fontFamily: 'Space Grotesk, sans-serif', fontSize: 'clamp(32px,5vw,52px)', fontWeight: 900, color: '#1a1a1a', letterSpacing: '-2px', marginBottom: 8 }}>
                {purpose ? purpose.charAt(0).toUpperCase() + purpose.slice(1) : 'Custom'} PC Build
              </h1>
              <p style={{ fontSize: 15, color: '#9ca3af' }}>Review your components and get buying links</p>
            </div>
          </motion.div>

          {/* Build Overview Card */}
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
            style={{ padding: '28px 32px', borderRadius: 16, background: '#ffffff', border: '2px solid #f5c800', boxShadow: '0 4px 24px rgba(245,200,0,0.15)', marginBottom: 32 }}>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 24 }}>
              <div>
                <p style={{ fontSize: 12, color: '#9ca3af', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: 4 }}>Total Cost</p>
                <h2 style={{ fontSize: 36, fontWeight: 900, color: '#1a1a1a', fontFamily: 'Space Grotesk, sans-serif' }}>₹{total.toLocaleString('en-IN')}</h2>
              </div>
              {budget && (
                <div>
                  <p style={{ fontSize: 12, color: '#9ca3af', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: 4 }}>Budget</p>
                  <h2 style={{ fontSize: 36, fontWeight: 900, color: total > budget ? '#ef4444' : '#16a34a', fontFamily: 'Space Grotesk, sans-serif' }}>₹{budget.toLocaleString('en-IN')}</h2>
                </div>
              )}
              <div>
                <p style={{ fontSize: 12, color: '#9ca3af', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: 4 }}>Components</p>
                <h2 style={{ fontSize: 36, fontWeight: 900, color: '#1a1a1a', fontFamily: 'Space Grotesk, sans-serif' }}>{Object.keys(selectedParts).length}</h2>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <motion.button whileHover={{ scale: 1.05, background: '#d4a900' }} whileTap={{ scale: 0.95 }}
                  onClick={exportBuild}
                  style={{ flex: 1, padding: '14px 24px', borderRadius: 12, border: 'none', cursor: 'pointer', background: '#f5c800', color: '#1a1a1a', fontSize: 14, fontWeight: 800, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, boxShadow: '0 4px 16px rgba(245,200,0,0.3)', transition: 'all 0.2s' }}>
                  <Download size={16} /> EXPORT
                </motion.button>
              </div>
            </div>
            {budget && total > budget && (
              <div style={{ marginTop: 20, padding: '12px 16px', background: '#fef2f2', borderRadius: 10, border: '1px solid #fecaca', fontSize: 13, color: '#ef4444', fontWeight: 600 }}>
                ⚠️ Over budget by ₹{(total - budget).toLocaleString('en-IN')}
              </div>
            )}
            {budget && total <= budget && (
              <div style={{ marginTop: 20, padding: '12px 16px', background: '#f0fdf4', borderRadius: 10, border: '1px solid #bbf7d0', fontSize: 13, color: '#16a34a', fontWeight: 600 }}>
                ✓ Within budget — ₹{(budget - total).toLocaleString('en-IN')} remaining
              </div>
            )}
          </motion.div>

          {/* Components List */}
          <div style={{ display: 'grid', gap: 20 }}>
            {Object.entries(selectedParts).map(([category, component], idx) => (
              <ComponentDetailCard key={category} category={category} component={component} index={idx} />
            ))}
          </div>

          {/* Bottom Actions */}
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 }}
            style={{ marginTop: 40, padding: '32px', borderRadius: 16, background: '#1a1a1a', textAlign: 'center' }}>
            <h3 style={{ fontSize: 24, fontWeight: 900, color: '#f5c800', fontFamily: 'Space Grotesk, sans-serif', marginBottom: 12 }}>
              Ready to Buy?
            </h3>
            <p style={{ fontSize: 14, color: '#9ca3af', marginBottom: 24 }}>
              Click the Amazon or Flipkart buttons on each component to purchase
            </p>
            <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
              <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
                onClick={() => navigate('/pc-builder')}
                style={{ padding: '14px 32px', borderRadius: 12, border: '2px solid rgba(255,255,255,0.2)', cursor: 'pointer', background: 'transparent', color: '#ffffff', fontSize: 14, fontWeight: 800, transition: 'all 0.2s' }}>
                Build Another PC
              </motion.button>
              <motion.button whileHover={{ scale: 1.05, background: '#d4a900' }} whileTap={{ scale: 0.95 }}
                onClick={exportBuild}
                style={{ padding: '14px 32px', borderRadius: 12, border: 'none', cursor: 'pointer', background: '#f5c800', color: '#1a1a1a', fontSize: 14, fontWeight: 800, display: 'flex', alignItems: 'center', gap: 8, boxShadow: '0 4px 16px rgba(245,200,0,0.3)', transition: 'all 0.2s' }}>
                <Download size={16} /> Download Build List
              </motion.button>
            </div>
          </motion.div>

        </div>
      </div>
    </PageWrapper>
  )
}

function ComponentDetailCard({ category, component, index }) {
  const lowestPrice = Math.min(component.price.amazon, component.price.flipkart)
  const amazonCheaper = component.price.amazon <= component.price.flipkart

  return (
    <motion.div
      initial={{ opacity: 0, x: -20 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ delay: index * 0.08 }}
      style={{ padding: '24px', borderRadius: 16, background: '#ffffff', border: '2px solid #f3f4f6', boxShadow: '0 2px 12px rgba(0,0,0,0.04)' }}>
      
      <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr auto', gap: 20, alignItems: 'center' }}>
        
        {/* Icon & Category */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{ width: 56, height: 56, borderRadius: 12, background: '#fff9d6', border: '2px solid #f5c800', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 28 }}>
            {component.img || '🔲'}
          </div>
          <div>
            <p style={{ fontSize: 11, color: '#9ca3af', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: 2 }}>{category}</p>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <Check size={14} color="#16a34a" strokeWidth={3} />
              <span style={{ fontSize: 11, color: '#16a34a', fontWeight: 700 }}>Selected</span>
            </div>
          </div>
        </div>

        {/* Component Details */}
        <div>
          <h3 style={{ fontSize: 16, fontWeight: 800, color: '#1a1a1a', marginBottom: 6 }}>{component.name}</h3>
          <p style={{ fontSize: 13, color: '#6b7280', lineHeight: 1.5, marginBottom: 12 }}>
            {typeof component.specs === 'string' ? component.specs : JSON.stringify(component.specs)}
          </p>
          
          {/* Price Comparison */}
          <div style={{ display: 'flex', gap: 16, alignItems: 'center' }}>
            <div>
              <span style={{ fontSize: 11, color: '#9ca3af', marginRight: 6 }}>Amazon</span>
              <span style={{ fontSize: 15, fontWeight: 800, color: amazonCheaper ? '#16a34a' : '#6b7280' }}>
                {component.price.amazon === 0 ? 'Free' : `₹${component.price.amazon.toLocaleString('en-IN')}`}
              </span>
              {amazonCheaper && component.price.amazon > 0 && (
                <span style={{ marginLeft: 6, fontSize: 10, fontWeight: 800, color: '#16a34a', background: '#f0fdf4', padding: '2px 6px', borderRadius: 4 }}>LOWEST</span>
              )}
            </div>
            <div>
              <span style={{ fontSize: 11, color: '#9ca3af', marginRight: 6 }}>Flipkart</span>
              <span style={{ fontSize: 15, fontWeight: 800, color: !amazonCheaper ? '#16a34a' : '#6b7280' }}>
                {component.price.flipkart === 0 ? 'Free' : `₹${component.price.flipkart.toLocaleString('en-IN')}`}
              </span>
              {!amazonCheaper && component.price.flipkart > 0 && (
                <span style={{ marginLeft: 6, fontSize: 10, fontWeight: 800, color: '#16a34a', background: '#f0fdf4', padding: '2px 6px', borderRadius: 4 }}>LOWEST</span>
              )}
            </div>
          </div>
        </div>

        {/* Buy Buttons */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10, minWidth: 140 }}>
          <motion.a whileHover={{ scale: 1.05, boxShadow: '0 4px 16px rgba(255,153,0,0.4)' }} whileTap={{ scale: 0.95 }}
            href={component.links?.amazon || `https://www.amazon.in/s?k=${encodeURIComponent(component.name)}`}
            target="_blank" rel="noopener noreferrer"
            style={{ padding: '12px 20px', borderRadius: 10, background: '#ff9900', color: 'white', textDecoration: 'none', fontSize: 13, fontWeight: 800, textAlign: 'center', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, boxShadow: '0 2px 8px rgba(255,153,0,0.3)', transition: 'all 0.2s' }}>
            <ShoppingCart size={14} /> Amazon <ExternalLink size={12} />
          </motion.a>
          <motion.a whileHover={{ scale: 1.05, boxShadow: '0 4px 16px rgba(40,116,240,0.4)' }} whileTap={{ scale: 0.95 }}
            href={component.links?.flipkart || `https://www.flipkart.com/search?q=${encodeURIComponent(component.name)}`}
            target="_blank" rel="noopener noreferrer"
            style={{ padding: '12px 20px', borderRadius: 10, background: '#2874f0', color: 'white', textDecoration: 'none', fontSize: 13, fontWeight: 800, textAlign: 'center', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, boxShadow: '0 2px 8px rgba(40,116,240,0.3)', transition: 'all 0.2s' }}>
            <ShoppingCart size={14} /> Flipkart <ExternalLink size={12} />
          </motion.a>
        </div>

      </div>
    </motion.div>
  )
}
