import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Cpu, ChevronRight, RotateCcw, Download, Check, ShoppingCart } from 'lucide-react'
import PageWrapper from '../components/PageWrapper'
import PurposeSelector from '../components/PurposeSelector'
import BudgetSlider from '../components/BudgetSlider'
import ComponentCard from '../components/ComponentCard'
import { cpuData, gpuData, ramData, storageData, motherboardData, psuData, caseData, monitorData, peripheralsData, getPCBudgetTier, getComponentsWithinBudget } from '../data/components'

const steps = ['Purpose', 'Budget', 'Results']

const SectionHeader = ({ label }) => (
  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
    <div style={{ width: 28, height: 28, borderRadius: 6, background: '#f5c800', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <Cpu size={14} color="#1a1a1a" />
    </div>
    <h3 style={{ fontSize: 15, fontWeight: 800, color: '#1a1a1a' }}>{label}</h3>
  </div>
)

export default function PCBuilderPage() {
  const [step, setStep] = useState(0)
  const [purpose, setPurpose] = useState('gaming')
  const [budget, setBudget] = useState(60000)
  const [selectedParts, setSelectedParts] = useState({})

  const tier = getPCBudgetTier(budget)

  const getComponents = () => getComponentsWithinBudget(purpose, budget)

  const selectPart = (cat, part) => setSelectedParts(prev => ({ ...prev, [cat]: part }))
  const isSelected = (cat, name) => selectedParts[cat]?.name === name
  const getTotal = () => Object.values(selectedParts).reduce((s, p) => s + Math.min(p.price.amazon, p.price.flipkart), 0)
  const reset = () => { setStep(0); setPurpose('gaming'); setBudget(60000); setSelectedParts({}) }

  const exportBuild = () => {
    const txt = `🖥️ MY PC BUILD — ${purpose.toUpperCase()}\nBudget: ₹${budget.toLocaleString('en-IN')}\nTotal: ₹${getTotal().toLocaleString('en-IN')}\n\n${Object.entries(selectedParts).map(([c, p]) => `${c}: ${p.name} — ₹${Math.min(p.price.amazon, p.price.flipkart).toLocaleString('en-IN')}`).join('\n')}\n\nGenerated by PCraft`
    const a = document.createElement('a')
    a.href = URL.createObjectURL(new Blob([txt], { type: 'text/plain' }))
    a.download = `pcraft-build-${Date.now()}.txt`
    a.click()
  }

  return (
    <PageWrapper>
      <div style={{ minHeight: 'calc(100vh - 64px)', background: '#fffef7', padding: '40px 24px' }}>
        <div style={{ maxWidth: 1400, margin: '0 auto' }}>

          {/* Header */}
          <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} style={{ textAlign: 'center', marginBottom: 40 }}>
            <span style={{ display: 'inline-block', fontSize: 11, fontWeight: 800, color: '#1a1a1a', background: '#f5c800', padding: '4px 14px', borderRadius: 20, letterSpacing: '1.5px', textTransform: 'uppercase', marginBottom: 14 }}>PC BUILDER</span>
            <h1 style={{ fontFamily: 'Space Grotesk, sans-serif', fontSize: 'clamp(32px,5vw,52px)', fontWeight: 900, color: '#1a1a1a', letterSpacing: '-2px' }}>BUILD YOUR PC.</h1>
            <p style={{ fontSize: 15, color: '#9ca3af', marginTop: 8 }}>Answer 2 quick questions and select your parts</p>
          </motion.div>

          {/* Step indicator */}
          <div style={{ display: 'flex', justifyContent: 'center', gap: 0, marginBottom: 40 }}>
            {steps.map((s, i) => (
              <div key={s} style={{ display: 'flex', alignItems: 'center' }}>
                <motion.div animate={{ scale: step === i ? 1.1 : 1 }}
                  style={{ width: 34, height: 34, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', background: i <= step ? '#f5c800' : '#f3f4f6', color: '#1a1a1a', fontWeight: 800, fontSize: 13, border: i <= step ? '2px solid #d4a900' : '2px solid #e5e7eb' }}>
                  {i < step ? '✓' : i + 1}
                </motion.div>
                <span style={{ marginLeft: 8, fontSize: 13, fontWeight: 700, color: i <= step ? '#1a1a1a' : '#9ca3af' }}>{s}</span>
                {i < steps.length - 1 && <div style={{ width: 40, height: 2, background: i < step ? '#f5c800' : '#e5e7eb', margin: '0 12px' }} />}
              </div>
            ))}
          </div>

          <AnimatePresence mode="wait">
            {/* Step 0 */}
            {step === 0 && (
              <motion.div key="s0" initial={{ opacity: 0, x: 40 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -40 }}>
                <div style={{ maxWidth: 540, margin: '0 auto', padding: 36, borderRadius: 16, background: '#ffffff', border: '2px solid #f3f4f6', boxShadow: '0 4px 24px rgba(0,0,0,0.06)' }}>
                  <PurposeSelector value={purpose} onChange={setPurpose} />
                  <motion.button whileHover={{ scale: 1.03, background: '#d4a900' }} whileTap={{ scale: 0.97 }}
                    onClick={() => setStep(1)}
                    style={{ marginTop: 24, width: '100%', padding: '16px', borderRadius: 12, border: 'none', cursor: 'pointer', background: '#f5c800', color: '#1a1a1a', fontSize: 16, fontWeight: 800, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, boxShadow: '0 4px 16px rgba(245,200,0,0.35)', transition: 'all 0.2s', letterSpacing: '0.3px' }}>
                    NEXT: SET BUDGET <ChevronRight size={18} />
                  </motion.button>
                </div>
              </motion.div>
            )}

            {/* Step 1 */}
            {step === 1 && (
              <motion.div key="s1" initial={{ opacity: 0, x: 40 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -40 }}>
                <div style={{ maxWidth: 540, margin: '0 auto', padding: 36, borderRadius: 16, background: '#ffffff', border: '2px solid #f3f4f6', boxShadow: '0 4px 24px rgba(0,0,0,0.06)' }}>
                  <BudgetSlider value={budget} onChange={setBudget} min={20000} max={300000} step={5000} label="Total PC Budget (INR)" />
                  <div style={{ marginTop: 18, padding: '12px 16px', background: '#fff9d6', borderRadius: 10, border: '1px solid #f5c800', fontSize: 13, color: '#6b7280' }}>
                    <strong style={{ color: '#1a1a1a' }}>Purpose:</strong> {purpose.charAt(0).toUpperCase() + purpose.slice(1)} &nbsp;·&nbsp;
                    <strong style={{ color: '#1a1a1a' }}>Tier:</strong> {tier.charAt(0).toUpperCase() + tier.slice(1)}
                  </div>
                  <div style={{ display: 'flex', gap: 10, marginTop: 20 }}>
                    <motion.button whileHover={{ scale: 1.02 }} onClick={() => setStep(0)}
                      style={{ flex: 1, padding: '15px', borderRadius: 12, border: '2px solid #e5e7eb', cursor: 'pointer', background: 'white', color: '#6b7280', fontSize: 15, fontWeight: 700, transition: 'all 0.2s' }}>
                      ← Back
                    </motion.button>
                    <motion.button whileHover={{ scale: 1.03, background: '#d4a900' }} whileTap={{ scale: 0.97 }} onClick={() => setStep(2)}
                      style={{ flex: 2, padding: '15px', borderRadius: 12, border: 'none', cursor: 'pointer', background: '#f5c800', color: '#1a1a1a', fontSize: 16, fontWeight: 800, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, boxShadow: '0 4px 16px rgba(245,200,0,0.35)', transition: 'all 0.2s', letterSpacing: '0.3px' }}>
                      SHOW MY BUILD <ChevronRight size={18} />
                    </motion.button>
                  </div>
                </div>
              </motion.div>
            )}

            {/* Step 2 */}
            {step === 2 && (
              <motion.div key="s2" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -30 }}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: 24 }}>
                  {/* Left: components */}
                  <div>
                    {/* Summary bar */}
                    <div style={{ padding: '18px 24px', borderRadius: 14, marginBottom: 28, display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 14, background: '#ffffff', border: '2px solid #f5c800', boxShadow: '0 4px 16px rgba(245,200,0,0.12)' }}>
                      <div>
                        <p style={{ fontSize: 11, color: '#9ca3af', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '1px' }}>Your Build</p>
                        <h2 style={{ fontSize: 20, fontWeight: 900, color: '#1a1a1a', marginTop: 2 }}>
                          {purpose.charAt(0).toUpperCase() + purpose.slice(1)} PC — {tier.charAt(0).toUpperCase() + tier.slice(1)} Tier
                        </h2>
                      </div>
                      <motion.button whileHover={{ scale: 1.03, background: '#f3f4f6' }} onClick={reset}
                        style={{ padding: '12px 22px', borderRadius: 10, border: '2px solid #e5e7eb', cursor: 'pointer', background: 'white', color: '#6b7280', fontSize: 14, fontWeight: 700, display: 'flex', alignItems: 'center', gap: 6, transition: 'all 0.2s' }}>
                        <RotateCcw size={15} /> Reset
                      </motion.button>
                    </div>

                    {Object.entries(getComponents()).map(([category, items], idx) => (
                      <motion.div key={category} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: idx * 0.05 }} style={{ marginBottom: 32 }}>
                        <SectionHeader label={category} />
                        {selectedParts[category] && (
                          <div style={{ marginBottom: 10, display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 11, background: '#f0fdf4', color: '#16a34a', padding: '3px 10px', borderRadius: 20, fontWeight: 700, border: '1px solid #bbf7d0' }}>
                            <Check size={11} /> {selectedParts[category].name} selected
                          </div>
                        )}
                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 14 }}>
                          {items.map((item, i) => (
                            <SelectableCard key={i} component={item} isSelected={isSelected(category, item.name)} onSelect={() => selectPart(category, item)} />
                          ))}
                        </div>
                      </motion.div>
                    ))}
                  </div>

                  {/* Right: Build Summary */}
                  <div style={{ position: 'sticky', top: 80, height: 'fit-content' }}>
                    <BuildSummary selectedParts={selectedParts} total={getTotal()} budget={budget} onExport={exportBuild} />
                  </div>
                </div>

                <style>{`@media(max-width:1024px){div[style*="grid-template-columns: 1fr 340px"]{grid-template-columns:1fr!important}div[style*="position: sticky"]{position:relative!important;top:0!important;margin-top:24px}}`}</style>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </PageWrapper>
  )
}

function SelectableCard({ component, isSelected, onSelect }) {
  const lowest = Math.min(component.price.amazon, component.price.flipkart)
  return (
    <motion.div whileHover={{ y: -4, boxShadow: '0 12px 32px rgba(245,200,0,0.18)' }}
      transition={{ type: 'spring', stiffness: 300, damping: 20 }}
      onClick={onSelect}
      style={{ padding: 18, borderRadius: 12, background: '#ffffff', border: isSelected ? '2px solid #f5c800' : '2px solid #f3f4f6', cursor: 'pointer', position: 'relative', transition: 'all 0.2s', boxShadow: isSelected ? '0 4px 16px rgba(245,200,0,0.2)' : 'none' }}>
      {isSelected && (
        <div style={{ position: 'absolute', top: 12, right: 12, width: 22, height: 22, borderRadius: '50%', background: '#f5c800', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <Check size={13} color="#1a1a1a" strokeWidth={3} />
        </div>
      )}
      {component.best && !isSelected && (
        <div style={{ position: 'absolute', top: 12, right: 12, fontSize: 9, fontWeight: 800, color: '#1a1a1a', background: '#f5c800', padding: '2px 8px', borderRadius: 20 }}>BEST</div>
      )}
      <div style={{ fontSize: 24, marginBottom: 8 }}>{component.img || '🔲'}</div>
      <h3 style={{ fontSize: 13, fontWeight: 800, color: '#1a1a1a', marginBottom: 5, paddingRight: 44 }}>{component.name}</h3>
      <p style={{ fontSize: 11, color: '#9ca3af', lineHeight: 1.5, marginBottom: 10 }}>
        {typeof component.specs === 'string' ? component.specs : JSON.stringify(component.specs)}
      </p>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 3 }}>
        <span style={{ fontSize: 11, color: '#9ca3af' }}>Amazon</span>
        <span style={{ fontSize: 12, fontWeight: 700, color: component.price.amazon <= component.price.flipkart ? '#16a34a' : '#6b7280' }}>
          {component.price.amazon === 0 ? 'Free' : `₹${component.price.amazon.toLocaleString('en-IN')}`}
        </span>
      </div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 10 }}>
        <span style={{ fontSize: 11, color: '#9ca3af' }}>Flipkart</span>
        <span style={{ fontSize: 12, fontWeight: 700, color: component.price.flipkart < component.price.amazon ? '#16a34a' : '#6b7280' }}>
          {component.price.flipkart === 0 ? 'Free' : `₹${component.price.flipkart.toLocaleString('en-IN')}`}
        </span>
      </div>
      <motion.button whileHover={{ scale: 1.02, background: isSelected ? '#d4a900' : '#f5c800' }} whileTap={{ scale: 0.98 }}
        onClick={(e) => { e.stopPropagation(); onSelect() }}
        style={{ width: '100%', padding: '11px', borderRadius: 9, border: 'none', cursor: 'pointer', background: isSelected ? '#f5c800' : '#f9fafb', color: '#1a1a1a', fontSize: 13, fontWeight: 800, marginBottom: 8, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, transition: 'all 0.2s', boxShadow: isSelected ? '0 3px 10px rgba(245,200,0,0.3)' : 'none' }}>
        {isSelected ? <><Check size={14} /> SELECTED</> : <><ShoppingCart size={14} /> SELECT THIS</>}
      </motion.button>
      <div style={{ display: 'flex', gap: 6 }}>
        <a href={component.links?.amazon || `https://www.amazon.in/s?k=${encodeURIComponent(component.name)}`} target="_blank" rel="noopener noreferrer" onClick={e => e.stopPropagation()}
          style={{ flex: 1, padding: '8px', borderRadius: 7, background: '#ff9900', color: 'white', textDecoration: 'none', fontSize: 12, fontWeight: 800, textAlign: 'center', boxShadow: '0 2px 6px rgba(255,153,0,0.3)' }}>Amazon ↗</a>
        <a href={component.links?.flipkart || `https://www.flipkart.com/search?q=${encodeURIComponent(component.name)}`} target="_blank" rel="noopener noreferrer" onClick={e => e.stopPropagation()}
          style={{ flex: 1, padding: '8px', borderRadius: 7, background: '#2874f0', color: 'white', textDecoration: 'none', fontSize: 12, fontWeight: 800, textAlign: 'center', boxShadow: '0 2px 6px rgba(40,116,240,0.3)' }}>Flipkart ↗</a>
      </div>
    </motion.div>
  )
}

function BuildSummary({ selectedParts, total, budget, onExport }) {
  const count = Object.keys(selectedParts).length
  const done = count >= 9
  return (
    <motion.div initial={{ opacity: 0, x: 40 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.3 }}
      style={{ padding: 24, borderRadius: 16, background: '#ffffff', border: '2px solid #f5c800', boxShadow: '0 4px 24px rgba(245,200,0,0.15)' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
        <div style={{ width: 36, height: 36, borderRadius: 8, background: '#f5c800', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <ShoppingCart size={18} color="#1a1a1a" />
        </div>
        <div>
          <h3 style={{ fontSize: 15, fontWeight: 800, color: '#1a1a1a' }}>Your Build</h3>
          <p style={{ fontSize: 11, color: '#9ca3af' }}>{count}/9 parts selected</p>
        </div>
      </div>

      <div style={{ height: 5, background: '#f3f4f6', borderRadius: 3, overflow: 'hidden', marginBottom: 16 }}>
        <motion.div initial={{ width: 0 }} animate={{ width: `${(count / 9) * 100}%` }} transition={{ type: 'spring', stiffness: 100 }}
          style={{ height: '100%', background: '#f5c800', borderRadius: 3 }} />
      </div>

      {count === 0 ? (
        <div style={{ textAlign: 'center', padding: '32px 16px', color: '#9ca3af' }}>
          <div style={{ fontSize: 36, marginBottom: 10 }}>🛒</div>
          <p style={{ fontSize: 13 }}>Click components to add to your build</p>
        </div>
      ) : (
        <>
          <div style={{ maxHeight: 280, overflowY: 'auto', marginBottom: 16 }}>
            {Object.entries(selectedParts).map(([cat, part]) => (
              <div key={cat} style={{ padding: '9px 0', borderBottom: '1px solid #f3f4f6' }}>
                <div style={{ fontSize: 10, color: '#9ca3af', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 2 }}>{cat}</div>
                <div style={{ fontSize: 12, fontWeight: 700, color: '#1a1a1a', marginBottom: 2 }}>{part.name}</div>
                <div style={{ fontSize: 13, fontWeight: 800, color: '#16a34a' }}>₹{Math.min(part.price.amazon, part.price.flipkart).toLocaleString('en-IN')}</div>
              </div>
            ))}
          </div>

          <div style={{ padding: '14px 0', borderTop: '2px solid #f3f4f6', borderBottom: '2px solid #f3f4f6', marginBottom: 16 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
              <span style={{ fontSize: 13, fontWeight: 700, color: '#6b7280' }}>Total</span>
              <span style={{ fontSize: 22, fontWeight: 900, color: '#1a1a1a', fontFamily: 'Space Grotesk, sans-serif' }}>₹{total.toLocaleString('en-IN')}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ fontSize: 12, color: '#9ca3af' }}>Budget</span>
              <span style={{ fontSize: 13, fontWeight: 700, color: total > budget ? '#ef4444' : '#16a34a' }}>₹{budget.toLocaleString('en-IN')}</span>
            </div>
            {total > budget && (
              <div style={{ marginTop: 8, padding: '7px 10px', background: '#fef2f2', borderRadius: 8, border: '1px solid #fecaca', fontSize: 11, color: '#ef4444' }}>
                ⚠️ Over budget by ₹{(total - budget).toLocaleString('en-IN')}
              </div>
            )}
            {total <= budget && total > 0 && (
              <div style={{ marginTop: 8, padding: '7px 10px', background: '#f0fdf4', borderRadius: 8, border: '1px solid #bbf7d0', fontSize: 11, color: '#16a34a' }}>
                ✓ Within budget — ₹{(budget - total).toLocaleString('en-IN')} remaining
              </div>
            )}
          </div>

          <motion.button whileHover={{ scale: 1.03, background: done ? '#d4a900' : '#f3f4f6' }} whileTap={{ scale: 0.97 }}
            onClick={onExport} disabled={!done}
            style={{ width: '100%', padding: '15px', borderRadius: 12, border: 'none', cursor: done ? 'pointer' : 'not-allowed', background: done ? '#f5c800' : '#f3f4f6', color: done ? '#1a1a1a' : '#9ca3af', fontSize: 15, fontWeight: 800, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, opacity: done ? 1 : 0.5, transition: 'all 0.2s', boxShadow: done ? '0 4px 16px rgba(245,200,0,0.3)' : 'none', letterSpacing: '0.3px' }}>
            <Download size={17} /> EXPORT BUILD LIST
          </motion.button>
          {!done && <p style={{ fontSize: 10, color: '#9ca3af', textAlign: 'center', marginTop: 8 }}>Select all 9 components to export</p>}
        </>
      )}
    </motion.div>
  )
}
